### ISSUE TITLE
TAB Order Reset Issue of Dropdown and DatePicker

### ISSUE THREAD

**Issue by VinodPillai-R** [radzenhq/radzen-blazor#155]
On a Blazor page with dropdowns and datepicker If you change item in dropdown using up/down arrows there is no issue. How ever if you select item using mouse selection from dropdown the TAB order resets to start and focus of the control is lost. Same 
![5PqT0WWosi](https://user-images.githubusercontent.com/86370143/123133162-1728b680-d46d-11eb-9c4b-0c5b13cc9c3d.gif)
issue is for datepicker also

**Comment by philiphendry** [comment]
I found a focus issue in a different component library and wondered how Radzen reacted and noticed that items selected with the mouse from a dropdown with a filter still have the problem shown above but also if you're typing in the filter and press tab the focus moves to the top of the document rather than the next control or at least closing the drop down and return focus to the original control. Worth creating a bug?

In the attached gif the first drop down works as expected but after I've entered "df" into the filter and press tab the focus has moved to the top of the document:
![RadzenDropdownFocusIssue](https://user-images.githubusercontent.com/705830/172778216-14b1bc4d-6328-466a-ad75-7a0d455334fc.gif)
