### ISSUE TITLE
Dropdown search

### ISSUE THREAD

**Issue by vinoopillai** [radzenhq/radzen-blazor#161]
Ability to search in dropdown without opening the dropdown list. When the focus is on the control list item to be selected based on the user input. If user inputs T the list to search and select first item based on that character and further search by up/down arrow from the current position in list . Somewhat like this
![jhrBBs2JVY](https://user-images.githubusercontent.com/86370143/123497146-84913e80-d649-11eb-856f-1f27454d660e.gif)

**Comment by bengavin** [comment]
Bumping this issue, this is a major user experience issue for our users who are used to normal browser dropdowns 'jumping' to the typeahead characters that they type.  Right now, for dropdowns without search/filter capability, no amount of typing one of the valid values results in that value being selected.  You can use the arrows to 'arrow down' to the value you want, but that is not great UX and definitely not accessible.

**Comment by hollow87** [comment]
Bumping this as there is a fix in a fork since June 15th 2022
This is a breaking feature for many CRUD applications. Many users will navigate CRUD pages with only the keyboard, being able to choose items in a dropdown by typing their first few letters is a standard feature that has been around for years.

**Comment by enchev** [comment]
Already supported
