### ISSUE TITLE
Version 5 conflict with Bootstrap

### ISSUE THREAD

**Issue by leon42** [radzenhq/radzen-blazor#1632]
In version 5.x there is a CSS conflict with Bootstrap.
I'm using the Default theme, but it appears to affect other themes as well.

In default-base.css there is this global CSS selector that sets the box-sizing:

*,
*::before,
*::after {
  box-sizing: inherit;
}

Bootstrap 4 and 5 have a similar selector that looks like this:

*,
*::before,
*::after {
  box-sizing: border-box;
}

Since it's global (not one of the .rz- selectors) I think it's overriding the Bootstrap selector and causing layout problems.
Specifically it affects the size of standard <input> text boxes. After updating the Radzen components to version 5, all of my text boxes  appeared too large.

e.g.

![image](https://github.com/user-attachments/assets/9f710058-5d40-42e5-92a3-cca6541b2bf4)

**Comment by yordanov** [comment]
Hi @leon42,

`box-sizing: inherit;` means that it will inherit the formerly set by Bootstrap `box-sizing: border-box;`

<img width="310" alt="image" src="https://github.com/user-attachments/assets/bfe6a293-e78a-468a-8653-c9b35e599018">

1. Make sure bootstrap.css is included before default-base.css
2. Clear you browser cache
4. I suspect this size change might be caused by a root font-size. Could you inspect the textbox and see what are the computed font-size and padding?
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/3c0e5814-3084-4b78-ab0b-f541b9dde4ab">

**Comment by psantoro3** [comment]
I ran into this issue as well with the bootstrap .nav class and the NavLink component after updating. It might be another point here to help figure out the bootstrap change/issue.

Comparing between Radzen 4.34.4 and 5.0.6 the only computed value to change is box-sizing. All padding and font stuff remained the same. In my case it is now inheriting to "content-type" when previously it was just set to "border-box".

**Comment by yordanov** [comment]
🤦🏻 Oh, misunderstood the issue! As @leon42 was refering to "text boxes" I initially thought it was `RadzenTextBox` component that got affected, while it was actually the standard `input` element Bootstrap styles being overridden by Radzen.

Thank you @psantoro3 and @leon42 for clarifying.

**Comment by richardaubin** [comment]
I just updated my app, and RadzenNumeric which originally had a w-100 class, the span's inner input is no longer sizing properly.
