### ISSUE TITLE
RadzenNumeric with TValue set to double does not correctly increment with the step up or step down buttons

### ISSUE THREAD

**Issue by Daeymon** [radzenhq/radzen-blazor#1667]
Step up or step down on RadzenNumeric is adding additional tiny decimals to the number on top of the designated step amount when TValue is set to "double".

To reproduce add the following to a default Radzen enabled Blazor project and click the step up or step down button a few times. The additional decimal doesn't get added on every step.
```
<RadzenNumeric TValue=double? Value=0.1 Step="0.1" />
```

![image](https://github.com/user-attachments/assets/1ba96e7b-137e-4827-a3ba-6b91a2c80568)
...press step up twice and then .....
![image](https://github.com/user-attachments/assets/12b386fe-6852-4f83-aea2-ded3a470fe7a)

This started happened after NuGet version 4.32.9 and is still happening in 5.1.2.

**Comment by enchev** [comment]
Looks like it's caused by this pull request: https://github.com/radzenhq/radzen-blazor/commit/98967410cb38d115e9a4bb0e1db4ac5aa22ae151
I'll check how to fix it.

**Comment by Cosmatevs** [comment]
I think that there were two solutions to this problem:
1. Use `decimal` instead of `double` or `float` if you need decimal precision. `double` and `float` types are meant to be approximations.
2. Use the `Format` attribute to show only some decimal places, and round the value when needed.

@enchev Converting floats and doubles to decimals will certainly work in most cases. However, `decimal` is not able to represent the full range of `float` and `double` types. For this reason, you may lose precision for numbers really close to zero and get conversion errors for large numbers. I'm not sure if this is intended – I was just concerned after seeing your commit.

**Comment by enchev** [comment]
Feel free to propose better solution.

**Comment by Cosmatevs** [comment]
@enchev I've already suggested two user-side solutions 😅 I think that it wasn't a problem with the Radzen component, it was just unrealistic expectations about the `double` and `float` types. Therefore, in my opinion, the responsibility for using appropriate types or solutions should lie with the developers using Radzen components, not with the developers of the Radzen. But that's just my opinion – perhaps there are better reasons to actually convert them to `decimal`.
