### ISSUE TITLE
RadzenNumericRangeValidator Fails Precision Validation for Decimal Ranges

### ISSUE THREAD

**Issue by goofy5752** [radzenhq/radzen-blazor#1763]
The `RadzenNumericRangeValidator` does not validate decimal ranges correctly due to precision issues. When setting `Min = 0` and `Max = 1`, the validator incorrectly allows decimal values between `1.01` and `1.49` to pass validation. Only values of `1.50` or higher trigger the validation error, which does not match expected behavior for decimal comparisons.

To Reproduce
------------

1.  Add a `RadzenNumeric` component to a form in a .NET 8 Blazor project.
2.  Apply `RadzenNumericRangeValidator` with `Min = 0` and `Max = 1`.
3.  Enter decimal values such as `1.01`, `1.25`, or `1.49`, which should trigger validation errors.
4.  Observe that the validator only triggers for values of `1.50` or higher.

Expected Behavior
-----------------

The validator should enforce strict decimal precision and throw validation errors for any values greater than `1`, including `1.01` to `1.49`.

Desktop
---------------------------------------------------

*   **OS**: Windows 11
*   **Browser**: Chrome
*   **Version**: Latest
*   **.NET Version**: .NET 8
*   **Radzen Version**: 4.32.4

**Comment by akorchev** [comment]
Hi @goofy5752,

This happens because 0 and 1 are by default parsed by Blazor as `int`.RadzenNumericRangeValidator converts the component value to the type of the `Min` and `Max` attributes. 1.5 converts to `2` while lesser numbers convert to `1` which is why validation passes. The solution is to specify the type of the Min and Max 

```
<RadzenNumericRangeValidator Min="0d" Max="1d" />
```

We will update the demo to include that so people don't get confused.
