### ISSUE TITLE
RadzenTabs: Connect selected tab with a query parameter in an efficient way

### ISSUE THREAD

**Issue by MPapst** [radzenhq/radzen-blazor#1779]
**Is your feature request related to a problem? Please describe.**
Hey,

I am looking for a way on how I can efficiently connect multiple RadzenTabs (over various pages in the application, maybe multiple on one page) to a Query Parameter of the URI.
With the current RadzenTabs implementation I would need to add a dictionary from Index to a descriptive name for every single tabs-component I am using.
As some of my tabs are dynamically generated based on database content, this shifts the indexes and a static dictionary would not be enough.

**Describe the solution you'd like**
I definitely would not like to have the component library manipulating my uri fragments or queries. But implementing a UniqueId (as in RadzenDataGridColumn) or a Tag Property that can work side by side with the `SelectedIndex` property and also provides a changed `EventCallback<string>` when it changes would be helpful. 

**Describe alternatives you've considered**
See above, the dictionary would be an alternative.. also wrapping the RadzenTabs and RadzenTabsItem component could work, but leads to a LOT of complexity on implementor side.

**Additional context**
Please let me know your thoughts - if you agree with my proposal, I would be happy to supply a pull request.

**Comment by akorchev** [comment]
We are doing something similar here: https://github.com/radzenhq/radzen-blazor/blob/master/RadzenBlazorDemos/Pages/GetStarted.razor

Would this help for your scenario?

**Comment by akorchev** [comment]
I don't think we should implement such capability at the moment. Here is why:

1. There already is a SelectedIndexChanged event. Adding SelectedTagChanged introduces ambiguity. What is the difference between those two events? 
2. What happens with SelectedTagChanged if the Tag attribute is not set?
3. If we implement it for RadzenTabs we should implement it for every other similar component as well (RadzenAccordion, RadzenPanelMenu, RadzenSteps etc).

I would suggest to wrap RadzenTabs (or inherit from it) and extend it with the required capabilities in order to avoid code duplication.

**Comment by MPapst** [comment]
Thanks, I totally understand that opinion.

Good thing I opened an issue before an PR :)
