### ISSUE TITLE
RadzenTemplateForm EditContext is not able to detect the field change bound to RadzenColorPicker

### ISSUE THREAD

**Issue by Owenll66** [radzenhq/radzen-blazor#1822]
**Describe the bug**
RadzenTemplateForm EditContext is not able to detect the field change bound to `RadzenColorPicker`

**To Reproduce**
I have a class named `Model` with a `Color` property which is bound to `RadzenColorPicker` as below:
```
<RadzenTemplateForm @ref="_form" Data="_model" Submit="(Model model) => OnFormSubmit(model)>
    <RadzenColorPicker @bind-Value="_model.Color" />
    <RadzenButton ButtonType="ButtonType.Submit" Text="Submit" />
</RadzenTemplateForm>

@code {
    RadzenTemplateForm<Model> _form;
    private Model _model = new();
    private void OnFormSubmit(Model model)
    {
        var modified = _form.EditContext.IsModified();
    }
}
```

When I pick a different color in the UI and click the submit button, `_form.EditContext.IsModified()` returns false.

**Expected behavior**
The form edit context should be able to detect the field change and `_form.EditContext.IsModified()` should return true when a different color is picked.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome: 131.0.6778.86 (Official Build) (64-bit)
 - Version: Radzen.Blazor 5.6.9

**Additional context**

**Comment by teneko** [comment]
`RadzenColorPicker` is not `EditContext`-aware. For example, it does not derive from `DataBoundFormComponent`, which implements `EditContext`-specific logic, resulting in no validation being applied.

There are several workarounds. Instead of using `@bind-Value`, you can separate `Value` and `ValueChanged`, and in `ValueChanged`, manually trigger the field change. This assumes you have a capable validator that can handle the model (e.g., a `model` of type `Model` with a field `Color`). 

Another approach is to retrieve the `EditContext` either via dependency injection (using `CascadingParameter`) or self-provisioning (see [[line 7](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-9.0#form-validation)](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-9.0#form-validation)) and implement validation for the field or model yourself. For an example, refer to the [[Blazor form validation documentation](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-9.0#form-validation)](https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/validation?view=aspnetcore-9.0#form-validation). By subscribing to `EditContext.OnValidationRequested`, you can be notified when the `EditContext` model needs validation. Similarly, subscribing to `EditContext.OnFieldChanged` notifies you when a field in the model (or sub-model) needs validation. Field-level validation is typically implemented for direct input components like `RadzenColorPicker`, while model-level validation is used for broader validation (e.g., upon form submission to display all validation messages).

This process can become unnecessarily complex, especially with multiple inputs lacking validation awareness. Ideally, the component should be made validation-aware, at the very least triggering `EditContext.NotifyFieldChanged`.
