### ISSUE TITLE
Unable to add a simple menu item in RadzenPanelMenu

### ISSUE THREAD

**Issue by RafaelMeloTrakx** [radzenhq/radzen-blazor#270]
I am getting "The render handle is not yet assigned." error message when I try to add a simple menu item dynamically. I am using Radzen.Blazor v3.9.6, the same error occurs in 3.11.12.

![image](https://user-images.githubusercontent.com/79855726/140649964-cf2600c9-0cee-452e-b97f-6f4e187e1758.png)

![image](https://user-images.githubusercontent.com/79855726/140649978-3fbf22a6-dae4-4a25-b25c-f719d2dca628.png)

I hope we can get a more stable version of Radzen components for Blazor soon in https://github.com/radzenhq/radzen-blazor.

**Comment by akorchev** [comment]
The AddItem method is for internal use and should not be used with components that are not part of the page. We will probably make it internal to avoid further confusion. In general using Blazor components like this isn't supported by the framework - you need to add a component to a .razor file in order to render it.

[Here](https://github.com/radzenhq/radzen-blazor/blob/master/RadzenBlazorDemos/Shared/MainLayout.razor#L85-L111) is an example how to dynamically add panel menu items.
