### ISSUE TITLE
Row Disapearing in DataGrid self-Reference Hierarchy Example

### ISSUE THREAD

**Issue by PrestigiousP** [radzenhq/radzen-blazor#947]
I noticed while trying your self-reference datagrid on your website that there is a bug. The row will disapear if we try to hide the childs using the expand button on the parent element. 

Here is how you can reproduce the bug: 

1- Be sure to have the childs visible (expand the parent element)
2- Open the Filter panel of Job Title
3 - Write in the first field the word "Representative" and click apply
4- Close the parent element

Now all the data should be gone and the message "No records to display." displayed.

**Comment by enchev** [comment]
Hi @PrestigiousP,

Child data in self-referenced DataGrid are loaded on demand when the parent row is expanded and cleared when the row is collapsed and since the parent row Job Title does not contain "Representative" no records will be displayed. You can avoid this by clearing the filters on collapse:
![image](https://user-images.githubusercontent.com/5804953/235598117-25c5f78e-988e-490b-a335-2a56fb2cc096.png)
